export const CategoriesEnum = [
  "Art",
  "Photography",
  "Travel",
  "Food and Drink",
  "Home Decor",
  "DIY and Crafts",
  "Fashion",
  "Beauty",
  "Health and Fitness",
  "Wedding",
  "Gardening",
  "Technology",
  "Cars and Motorcycles",
  "Architecture",
  "Education",
  "Animals",
  "Parenting",
  "Humor",
  "Sports",
  "Entertainment",
  "Quotes",
  "History",
  "Books",
  "Movies",
  "Music",
  "Nature",
  "Business",
  "Finance",
  "Science",
  "Outdoors",
  "Spirituality",
  "Gaming",
  "Celebrities",
  "Jewelry",
  "Tattoo",
  "Men’s Fashion",
  "Women’s Fashion",
  "Street Style",
  "Interior Design",
];
export const ReportCommentsEnum = [
  "Abusive",
  "Sexual",
  "Spam",
  "Harassment",
  "Hate Speech",
  "Miscellaneous",
];
export const ReportPostEnum = [
  "Abusive",
  "Sexual",
  "Spam",
  "Promoting Voilence",
  "Spreading hate",
  "Miscellaneous",
];

export const ReportUserEnum = [
  "Spam Account",
  "Impersonation",
  "Harassment",
  "Scam",
  "Inappropriate Content",
  "Fake Account",
  "Trolling",
  "Hate Speech",
  "Miscellaneous",
];

